version: "3.3"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
            - mongo
            - redis
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: ""
            ACCEPT_EULA: "Y"
        ports: 
          - "1433:1433"
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
    redis:
        image: redis
        ports:
          - "6379:6379"
